# Generated by Django 5.2.3 on 2025-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newssearchconfig",
            name="domains",
        ),
        migrations.RemoveField(
            model_name="newssearchconfig",
            name="exclude_domains",
        ),
        migrations.RemoveField(
            model_name="newssearchconfig",
            name="language",
        ),
        migrations.AddField(
            model_name="newssearchconfig",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("business", "Business"),
                    ("technology", "Technology"),
                ],
                default="general",
                help_text="Category to get headlines for",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newssearchconfig",
            name="country",
            field=models.CharField(
                choices=[
                    ("us", "United States"),
                    ("uk", "United Kingdom"),
                    ("ca", "Canada"),
                ],
                default="us",
                help_text="Country to get headlines for",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="newssearchconfig",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="Keywords or phrases to search for"
            ),
        ),
    ]
