# Generated by Django 5.2.3 on 2025-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_config", "0002_remove_newssearchconfig_domains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="source_id",
            field=models.CharField(
                blank=True,
                help_text="NewsAPI source identifier",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="author",
            field=models.CharField(
                blank=True, help_text="Article author", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Truncated article content (max 200 chars)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(
                blank=True, help_text="Article snippet or description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="is_read",
            field=models.BooleanField(default=False, help_text="User read status"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(help_text="Publication date and time"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="source_name",
            field=models.CharField(help_text="Source name", max_length=200),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.TextField(help_text="Article headline"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url",
            field=models.URLField(help_text="Direct URL to the article", unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="url_to_image",
            field=models.URLField(
                blank=True, help_text="URL to article image", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["published_at"], name="news_config_publish_f96f0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source_name"], name="news_config_source__aba887_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["is_read"], name="news_config_is_read_75bef3_idx"
            ),
        ),
    ]
