name: Deploy

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync

      - name: Build package
        run: |
          uv build

      - name: Deploy to staging
        run: |
          echo "Deploy to staging environment"
          # Add your staging deployment commands here
          # Example: rsync, docker push, kubectl apply, etc.

      - name: Run smoke tests
        run: |
          echo "Running smoke tests against staging"
          # Add smoke tests for your deployed application

      - name: Deploy to production
        if: github.event_name == 'release'
        run: |
          echo "Deploy to production environment"
          # Add your production deployment commands here

      - name: Notify deployment
        if: always()
        run: |
          echo "Deployment completed with status: ${{ job.status }}"
          # Add notification logic (Slack, email, etc.)
